version: "3.5"

# TODO: pull images from docker hub


services:
  db:
    image: swim-postgres
    build:
      context: ./
      dockerfile: ./services/db/postgres/Dockerfile
    container_name: postgres
    environment:
      - DB_NAME=smdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./services/db/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/etc/postgresql.conf
    networks:
      - backend

  broker:
    image: rabbitmq_amqp10
    hostname: rabbitmq
    build:
      context: ./
      dockerfile: ./services/broker/rabbitmq/Dockerfile
      args:
        - BROKER_ADMIN_USER=${BROKER_ADMIN_USER}
        - BROKER_ADMIN_PASS=${BROKER_ADMIN_PASS}
    container_name: rabbitmq
    ports:
      - 15671:15671
    volumes:
      - broker-data:/var/lib/rabbitmq
      - ./secrets/rabbitmq/rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
    networks:
      - backend

  web-server:
    image: swim-nginx
    build:
      context: ./
      dockerfile: ./services/web_server/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:8000
      - 443:8443
    volumes:
      - ./services/web_server/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - subscription-manager
    networks:
      - backend

  subscription-manager:
    image: subscription-manager
    build: ./services/subscription_manager/src
    container_name: subscription_manager
    depends_on:
      - db
      - broker
    environment:
      - DB_NAME=smdb
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - BROKER_MGMT_USER=${BROKER_MGMT_USER}
      - BROKER_MGMT_PASS=${BROKER_MGMT_PASS}
    volumes:
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/ca_certificate.pem
      - ./services/subscription_manager/config.yml:/app/subscription_manager/_config.yml
      - ./services/subscription_manager/entry.sh:/app/entry.sh
    command: bash /app/entry.sh
    networks:
      - backend

  subscription-manager-provision:
    image: subscription-manager
    build: ./services/subscription_manager/src
    container_name: subscription_manager_provision
    depends_on:
      - broker
      - db
    environment:
      - DB_NAME=smdb
      - SWIM_EXPLORER_BROKER_USER=${SWIM_EXPLORER_BROKER_USER}
      - SWIM_EXPLORER_BROKER_PASS=${SWIM_EXPLORER_BROKER_PASS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SM_ADMIN_USER=${SM_ADMIN_USER}
      - SM_ADMIN_PASS=${SM_ADMIN_PASS}
      - SWIM_ADSB_SM_USER=${SWIM_ADSB_SM_USER}
      - SWIM_ADSB_SM_PASS=${SWIM_ADSB_SM_PASS}
      - SWIM_EXPLORER_SM_USER=${SWIM_EXPLORER_SM_USER}
      - SWIM_EXPLORER_SM_PASS=${SWIM_EXPLORER_SM_PASS}
      - BROKER_MGMT_USER=${BROKER_MGMT_USER}
      - BROKER_MGMT_PASS=${BROKER_MGMT_PASS}
      - BROKER_ADMIN_USER=${BROKER_ADMIN_USER}
      - BROKER_ADMIN_PASS=${BROKER_ADMIN_PASS}
    volumes:
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/ca_certificate.pem
      - ./services/subscription_manager/provision/config.yml:/app/provision/_config.yml
      - ./services/subscription_manager/provision/entry.sh:/app/entry.sh
    command: bash entry.sh
    networks:
      - backend

  swim-adsb:
    image: swim-adsb
    build: ./services/swim_adsb/src
    container_name: swim_adsb
    depends_on:
      - subscription-manager
      - web-server
    environment:
      - SWIM_ADSB_SM_USER=${SWIM_ADSB_SM_USER}
      - SWIM_ADSB_SM_PASS=${SWIM_ADSB_SM_PASS}
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_adsb/config.yml:/app/swim_adsb/_config.yml
      - ./services/swim_adsb/entry.sh:/app/entry.sh
    command: bash /app/entry.sh
    networks:
      - backend


  swim-explorer:
    image: swim-explorer
    build: ./services/swim_explorer/src
    container_name: swim_explorer
    depends_on:
      - subscription-manager
      - web-server
      - swim-adsb
    environment:
      - SWIM_EXPLORER_BROKER_USER=${SWIM_EXPLORER_BROKER_USER}
      - SWIM_EXPLORER_BROKER_PASS=${SWIM_EXPLORER_BROKER_PASS}
      - SWIM_EXPLORER_SM_USER=${SWIM_EXPLORER_SM_USER}
      - SWIM_EXPLORER_SM_PASS=${SWIM_EXPLORER_SM_PASS}
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_explorer/config.yml:/app/swim_explorer/_config.yml
      - ./services/swim_explorer/entry.sh:/app/entry.sh
    ports:
      - 5000:5000
    command: bash /app/entry.sh
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
  broker-data:
    driver: local


